#!/usr/bin/env python3
"""Rebuild the standalone static site (live/) from the Claude Design canvas project.

Usage:
    # 1. serve the project root and capture the runtime-rendered DOM
    python3 -m http.server 8734 &
    chrome --headless --virtual-time-budget=25000 --dump-dom \
        "http://localhost:8734/design/IBBRU%20Home.dc.html" > /tmp/live_dom.html

    # 2. regenerate live/
    python3 tools/build-live.py /tmp/live_dom.html

What it does:
  * styles.css  = the Nocturne design-system stylesheet + the page's own <style> block
  * index.html  = the rendered DOM (editor annotations and reveal artefacts stripped),
                  with a mobile-nav panel, a reader mount point and the case data injected
  * assets      = hero image + favicon

app.js is hand-written and is NOT regenerated by this script.
"""
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / "design"
LIVE = ROOT / "live"
SRC = DESIGN / "IBBRU Home.dc.html"
DUMP = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/live_dom.html")

if not SRC.exists():
    sys.exit(f"missing design source: {SRC}")
if not DUMP.exists():
    sys.exit(f"missing DOM dump: {DUMP} (see module docstring)")

src_html = SRC.read_text(encoding="utf-8")
dump = DUMP.read_text(encoding="utf-8")

# ---------------------------------------------------------------- styles.css
ds_css_path = next(DESIGN.glob("_ds/*/styles.css"))
ds_css = ds_css_path.read_text(encoding="utf-8")
helmet = src_html[src_html.index("<helmet>"):src_html.index("</helmet>")]
inline_css = "\n\n".join(re.findall(r"<style[^>]*>(.*?)</style>", helmet, re.S))
css = (
    "/* ============================================================\n"
    "   IBBRU — live site stylesheet (generated; see tools/build-live.py)\n"
    "   Part 1: Nocturne design system (tokens + components)\n"
    "   Part 2: IBBRU page styles\n"
    "   ============================================================ */\n\n"
    + ds_css + "\n\n/* ===== Part 2: IBBRU page styles ===== */\n" + inline_css
)
# asset URLs in the stylesheet (hero background) must point at live/assets/
css = css.replace("uploads/hero2.gif", "assets/hero.gif").replace("uploads/", "assets/")

# ---------------------------------------------------------------- body content
i = dump.index('<div data-dc-tpl="9" class="ib-page-bg"')
j = dump.index("<script", i)
content = dump[i:j]
content = re.sub(r'\s*data-dc-tpl="\d+"', "", content)
content = re.sub(r'\s*data-ib-shown="\d+"', "", content)
content = re.sub(
    r"\s*transition:\s*opacity\s*0?\.8s\s*cubic-bezier\([^)]*\),\s*transform\s*0?\.8s\s*cubic-bezier\([^)]*\);?",
    "", content)
content = content.replace(" opacity: 1; transform: none;", "").replace("opacity: 1; transform: none;", "")
content = content.replace(" opacity: 0; transform: translateY(26px);", "")
content = re.sub(r'<template[^>]*id="__bundler_thumbnail".*?</template>', "", content, flags=re.S)


# placeholders are removed entirely: founder photo frames, the dashed "seat", stray slots
content = re.sub(
    r'<div[^>]*style="flex:\s*0 0 auto;[^"]*"[^>]*>\s*<image-slot[^>]*>\s*</image-slot>\s*</div>',
    "", content)
content = re.sub(r'<div[^>]*1\.5px dashed[^>]*>Your seat</div>', "", content)
content = re.sub(r"<image-slot[^>]*>\s*</image-slot>", "", content)
content = content.replace("uploads/hero2.gif", "assets/hero.gif").replace("uploads/", "assets/")

MOBILE_NAV = """
  <div id="ib-mobile-nav" style="display:none; position:fixed; inset:0; z-index:49; background: color-mix(in srgb, var(--color-bg) 96%, transparent); backdrop-filter: blur(8px); flex-direction: column; justify-content: center; gap: var(--space-4); padding: 0 clamp(24px,8vw,72px);">
    <a href="#work" style="font-family: var(--font-heading); font-size: 34px; color: var(--color-text); text-decoration: none;">Work</a>
    <a href="#services" style="font-family: var(--font-heading); font-size: 34px; color: var(--color-text); text-decoration: none;">Services</a>
    <a href="#about" style="font-family: var(--font-heading); font-size: 34px; color: var(--color-text); text-decoration: none;">About</a>
    <a href="#focus" style="font-family: var(--font-heading); font-size: 34px; color: var(--color-text); text-decoration: none;">Insights</a>
    <a href="#contact" style="font-family: var(--font-heading); font-size: 34px; color: var(--color-text); text-decoration: none;">Contact</a>
  </div>
"""
content = content.replace("</nav>", "</nav>" + MOBILE_NAV, 1)
content = content.replace(
    '<div class="ib-shelf"',
    '<div id="ib-reader" hidden aria-live="polite"></div>\n      <div class="ib-shelf"', 1)

# ---------------------------------------------------------------- case data
m = re.search(r"const rawWork = (\[.*?\n    \]);", src_html, re.S)
if not m:
    sys.exit("could not find rawWork data in the design file")
tmp_js = Path("/tmp/_workdata.js")
tmp_js.write_text("const rawWork = " + m.group(1) + ";console.log(JSON.stringify(rawWork));", encoding="utf-8")
work = json.loads(subprocess.check_output(["node", str(tmp_js)]).decode())

# ---------------------------------------------------------------- write live/
(LIVE / "assets").mkdir(parents=True, exist_ok=True)
EXTRA_CSS = """
/* ===== live-site additions (static build) ===== */
.js [data-reveal] { opacity: 0; transform: translateY(26px); }
.js [data-reveal].ib-in { opacity: 1; transform: none;
  transition: opacity .8s cubic-bezier(.22,.61,.36,1), transform .8s cubic-bezier(.22,.61,.36,1); }
@media (prefers-reduced-motion: reduce) {
  .js [data-reveal] { opacity: 1 !important; transform: none !important; transition: none !important; }
}
#ib-reader[hidden], .ib-shelf[hidden] { display: none !important; }
body.ib-locked { overflow: hidden; }
#ib-reader .ib-open { margin-top: 0; }
"""
(LIVE / "styles.css").write_text(css + EXTRA_CSS, encoding="utf-8")

html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>IBBRU — Complexity, made simple.</title>
<meta name="description" content="IBBRU is an independent product design studio. We help teams solve problems, design better experiences, and build usable products.">
<meta property="og:title" content="IBBRU — Complexity, made simple.">
<meta property="og:description" content="Independent product design studio — product strategy, enterprise UX, design systems, 0-to-1 product design and brand video.">
<meta property="og:type" content="website">
<link rel="icon" href="assets/favicon.svg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&amp;display=swap">
<link rel="stylesheet" href="styles.css">
<script>document.documentElement.classList.add('js');</script>
</head>
<body>
""" + content + """
<script type="application/json" id="ib-data">""" + json.dumps(work, ensure_ascii=False).replace("</", "<\\/") + """</script>
<script src="app.js" defer></script>
<script>setTimeout(function(){document.querySelectorAll('[data-reveal]').forEach(function(e){e.classList.add('ib-in')})},3000);</script>
</body>
</html>
"""
(LIVE / "index.html").write_text(html, encoding="utf-8")

favicon = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'
    '<rect width="64" height="64" rx="14" fill="#161826"/>'
    '<text x="32" y="43" font-family="Inter, system-ui, sans-serif" font-weight="700" '
    'font-size="30" letter-spacing="1" fill="#e9e9ed" text-anchor="middle">IB</text>'
    '<circle cx="32" cy="51" r="2.6" fill="#9184d9"/></svg>'
)
(LIVE / "assets" / "favicon.svg").write_text(favicon, encoding="utf-8")
shutil.copy(DESIGN / "uploads" / "hero2.gif", LIVE / "assets" / "hero.gif")

print("rebuilt live/ — books:", [(g["group"], len(g["cases"])) for g in work])