#!/usr/bin/env python3
"""Rebuild the standalone static site (live/) from the Claude Design canvas project.

Usage:
    # 1. serve the project root and capture the runtime-rendered DOM
    python3 -m http.server 8734 &
    chrome --headless --virtual-time-budget=25000 --dump-dom \
        "http://localhost:8734/design/IBBRU%20Home.dc.html" > /tmp/live_dom.html

    # 2. regenerate live/
    python3 tools/build-live.py /tmp/live_dom.html

What it does:
  * styles.css  = the Nocturne design-system stylesheet + the page's own <style> block
  * index.html  = the rendered DOM (editor annotations, reveal artefacts and the visual
                  editor's viewport-snapshot styles stripped), with a contact modal,
                  mobile-nav panel, reader mount point and the case data injected
  * assets/     = every image the page references, copied out of design/uploads/

app.js is hand-written and is NOT regenerated by this script.
"""
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DESIGN = ROOT / "design"
LIVE = ROOT / "live"
SRC = DESIGN / "IBBRU Home.dc.html"
DUMP = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/live_dom.html")

if not SRC.exists():
    sys.exit(f"missing design source: {SRC}")
if not DUMP.exists():
    sys.exit(f"missing DOM dump: {DUMP} (see module docstring)")

src_html = SRC.read_text(encoding="utf-8")
dump = DUMP.read_text(encoding="utf-8")

# ---------------------------------------------------------------- styles.css
ds_css = next(DESIGN.glob("_ds/*/styles.css")).read_text(encoding="utf-8")
helmet = src_html[src_html.index("<helmet>"):src_html.index("</helmet>")]
inline_css = "\n\n".join(re.findall(r"<style[^>]*>(.*?)</style>", helmet, re.S))
css = (
    "/* ============================================================\n"
    "   IBBRU — live site stylesheet (generated; see tools/build-live.py)\n"
    "   Part 1: Nocturne design system (tokens + components)\n"
    "   Part 2: IBBRU page styles\n"
    "   ============================================================ */\n\n"
    + ds_css + "\n\n/* ===== Part 2: IBBRU page styles ===== */\n" + inline_css
)

# ---------------------------------------------------------------- body content
i = dump.index('<div data-dc-tpl="9" class="ib-page-bg"')
j = dump.index("<script", i)
content = dump[i:j]

content = re.sub(r'\s*data-dc-tpl="\d+"', "", content)
content = re.sub(r'\s*data-ib-shown="\d+"', "", content)
content = re.sub(
    r"\s*transition:\s*opacity\s*0?\.8s\s*cubic-bezier\([^)]*\),\s*transform\s*0?\.8s\s*cubic-bezier\([^)]*\);?",
    "", content)
content = content.replace(" opacity: 1; transform: none;", "").replace("opacity: 1; transform: none;", "")
content = content.replace(" opacity: 0; transform: translateY(26px);", "")
content = re.sub(r'<template[^>]*id="__bundler_thumbnail".*?</template>', "", content, flags=re.S)
content = content.replace('style="position: static;"', "").replace(" position: static;", "")


def map_styles(html, marker, fn):
    """Rewrite every style attribute whose value contains `marker`."""
    def sub(m):
        v = m.group(1)
        return 'style="%s"' % (fn(v) if marker in v else v)
    return re.sub(r'style="([^"]*)"', sub, html)


# placeholders are removed entirely: founder photo frames, the dashed "seat", stray slots
content = re.sub(
    r'<div[^>]*style="flex:\s*0 0 auto;[^"]*"[^>]*>\s*<image-slot[^>]*>\s*</image-slot>\s*</div>',
    "", content)
content = re.sub(r'<div[^>]*1\.5px dashed[^>]*>Your seat</div>', "", content)
content = re.sub(r"<image-slot[^>]*>\s*</image-slot>", "", content)

# page background: the editor replaced the theme gradient with a flat (light) colour
PAGE_BG = ("font-family: var(--font-body); color: var(--color-text); "
           "background: radial-gradient(1200px 720px at 82% -180px, "
           "color-mix(in srgb, var(--color-accent-900) 72%, transparent), transparent 60%), "
           "radial-gradient(1100px 900px at -12% 102%, color-mix(in srgb, black 30%, transparent), "
           "transparent 55%), var(--color-bg); min-height: 100vh; overflow-x: hidden; text-wrap: pretty;")
content = re.sub(r'(<div class="ib-page-bg"[^>]*?)\s+style="[^"]*"', lambda m: m.group(1) + ' style="' + PAGE_BG + '"', content, count=1)

# ---- neutralise the visual editor's viewport snapshot styles (live build only) ----
# hero: drop the pixel geometry so the .ib-hero-* classes drive the layout
content = re.sub(r'(<div[^>]*class="ib-hero-media"[^>]*?)\s+style="[^"]*"', r"\1", content)
content = re.sub(r'(<img[^>]*class="ib-hero-img"[^>]*?)\s+style="[^"]*"', r"\1", content)
content = re.sub(r'(<div[^>]*class="ib-hero-inner"[^>]*?)\s+style="[^"]*"', r"\1", content)
content = re.sub(r'(<div[^>]*class="ib-hero-copy"[^>]*?)\s+style="[^"]*"', r"\1", content)
# about stat panels: fixed height / offset / broken border longhands, and display:block
content = map_styles(
    content, "grid-template-columns: 1fr 1fr;",
    lambda v: "display: grid; grid-template-columns: 1fr 1fr; border-radius: var(--radius-lg); overflow: hidden;")
content = map_styles(
    content, "justify-content: space-between; gap: 32px;",
    lambda v: v.replace("display: block", "display: flex")
               .replace("margin-top: 0px;", "").replace("border-radius: 8px;", ""))
# process-section dolls: fixed left offset -> pinned right (and hidden on phones)
content = map_styles(content, "left: 988px;", lambda v: v.replace("left: 988px;", "right: -12px;"))
# about stat panel #2: the editor baked in a light-mode background colour
def _panel_bg(v):
    if "background-color:" in v and "justify-content: space-between" in v:
        v = re.sub(r"background-color:\s*[^;]+;?\s*", "", v)
        v += "background: color-mix(in srgb, var(--color-neutral-900) 55%, transparent);"
    return v
content = re.sub(r'style="([^"]*)"', lambda m: 'style="%s"' % _panel_bg(m.group(1)), content)


def mark_proc_doll(m):
    tag = m.group(0)
    if "position: absolute" in tag and re.search(r"top: 25[89]px", tag):
        return tag.replace('class="ib-float-b"', 'class="ib-float-b ib-proc-doll"').replace(
            'class="ib-float"', 'class="ib-float ib-proc-doll"')
    return tag


content = re.sub(r"<svg[^>]*>", mark_proc_doll, content)

# ---- contact modal trigger ----
content = re.sub(r"<button([^>]*)>(Start a conversation)", r"<button data-open-contact\1>\2", content, count=1)

# ---------------------------------------------------------------- contact modal
MODAL = """
<div id="ib-modal-root" hidden>
  <div class="ib-modal-backdrop" role="dialog" aria-modal="true" aria-label="Contact form">
    <div class="ib-modal">
      <div class="ib-modal-sent" hidden>
        <div style="font-size:32px; margin-bottom:12px;">✓</div>
        <h3 style="margin:0 0 8px;">Message sent!</h3>
        <p style="font-size:15px; color:color-mix(in srgb,var(--color-text) 68%,transparent); margin:0 0 24px;">We'll get back to you soon.</p>
        <button type="button" class="btn btn-secondary" data-modal="close">Close</button>
      </div>
      <div class="ib-modal-form">
        <div style="display:flex; justify-content:space-between; align-items:flex-start; gap:16px;">
          <div>
            <h3>Start a conversation</h3>
            <p style="font-size:14px; color:color-mix(in srgb,var(--color-text) 60%,transparent); margin:6px 0 0;">We'll read every message personally.</p>
          </div>
          <button type="button" class="btn btn-ghost btn-icon" data-modal="close" aria-label="Close" style="flex:none;">✕</button>
        </div>
        <div class="ib-modal-field"><label for="ib-c-name">Your name</label><input id="ib-c-name" type="text" placeholder="e.g. Alex"></div>
        <div class="ib-modal-field"><label for="ib-c-email">Your email</label><input id="ib-c-email" type="email" placeholder="you@company.com"></div>
        <div class="ib-modal-field"><label for="ib-c-msg">What's keeping you up at night?</label><textarea id="ib-c-msg" rows="4" placeholder="Tell us about the problem…"></textarea></div>
        <div class="ib-modal-actions">
          <button type="button" class="btn btn-secondary" data-modal="close">Cancel</button>
          <button type="button" class="btn btn-primary" data-modal="submit">Send message →</button>
        </div>
      </div>
    </div>
  </div>
</div>
"""

# ---------------------------------------------------------------- mobile nav + reader mount
MOBILE_NAV = """
  <div id="ib-mobile-nav" style="display:none; position:fixed; inset:0; z-index:49; background: color-mix(in srgb, var(--color-bg) 96%, transparent); backdrop-filter: blur(8px); flex-direction: column; justify-content: center; gap: var(--space-4); padding: 0 clamp(24px,8vw,72px);">
    <a href="#work" style="font-family: var(--font-heading); font-size: 34px; color: var(--color-text); text-decoration: none;">Work</a>
    <a href="#services" style="font-family: var(--font-heading); font-size: 34px; color: var(--color-text); text-decoration: none;">Services</a>
    <a href="#about" style="font-family: var(--font-heading); font-size: 34px; color: var(--color-text); text-decoration: none;">About</a>
    <a href="#insights" style="font-family: var(--font-heading); font-size: 34px; color: var(--color-text); text-decoration: none;">Focus</a>
    <a href="#contact" style="font-family: var(--font-heading); font-size: 34px; color: var(--color-text); text-decoration: none;">Contact</a>
  </div>
"""
content = content.replace("</nav>", "</nav>" + MOBILE_NAV, 1)
content = content.replace(
    '<div class="ib-shelf"',
    '<div id="ib-reader" hidden aria-live="polite"></div>\n      <div class="ib-shelf"', 1)

# ---------------------------------------------------------------- case data
m = re.search(r"const rawWork = (\[.*?\n    \]);", src_html, re.S)
if not m:
    sys.exit("could not find rawWork data in the design file")
tmp_js = Path("/tmp/_workdata.js")
tmp_js.write_text("const rawWork = " + m.group(1) + ";console.log(JSON.stringify(rawWork));", encoding="utf-8")
work = json.loads(subprocess.check_output(["node", str(tmp_js)]).decode())

# ---------------------------------------------------------------- assets
(LIVE / "assets").mkdir(parents=True, exist_ok=True)
for stale in (LIVE / "assets").glob("*"):
    stale.unlink()
refs = sorted(set(re.findall(r"uploads/([A-Za-z0-9_.\- ]+)", content + css)))
for ref in refs:
    src = DESIGN / "uploads" / ref
    if src.exists():
        shutil.copy(src, LIVE / "assets" / ref)
    else:
        print("  ! referenced asset missing:", ref)
content = content.replace("uploads/", "assets/")
css = css.replace("uploads/", "assets/")

# ---------------------------------------------------------------- write live/
EXTRA_CSS = """
/* ===== live-site additions (static build) ===== */
.js [data-reveal] { opacity: 0; transform: translateY(26px); }
.js [data-reveal].ib-in { opacity: 1; transform: none;
  transition: opacity .8s cubic-bezier(.22,.61,.36,1), transform .8s cubic-bezier(.22,.61,.36,1); }
@media (prefers-reduced-motion: reduce) {
  .js [data-reveal] { opacity: 1 !important; transform: none !important; transition: none !important; }
}
#ib-reader[hidden], .ib-shelf[hidden], #ib-modal-root[hidden],
.ib-modal-sent[hidden], .ib-modal-form[hidden] { display: none !important; }
body.ib-locked { overflow: hidden; }
#ib-reader .ib-open { margin-top: 0; }
/* hero artwork: editor px geometry translated to a proportional, responsive band */
.ib-hero-img { top: 9%; right: 0; left: auto; bottom: auto; width: min(1300px, 84%); height: auto; object-fit: contain;
  -webkit-mask-image: linear-gradient(to right, transparent 0, #000 15%);
  mask-image: linear-gradient(to right, transparent 0, #000 15%); }
@media (max-width: 720px) {
  .ib-hero-inner { max-width: none; }
  .ib-hero-media-inner { max-width: none; }
  .ib-hero-img { width: 100%; height: 46%; top: auto; bottom: 0; object-fit: cover; }
}
@media (max-width: 860px) {
  .ib-proc-doll { display: none !important; }
  /* the stat panels' desktop alignment offset is meaningless once stacked */
  [style*="margin-top: 171px"] { margin-top: 0 !important; }
}
"""
(LIVE / "styles.css").write_text(css + EXTRA_CSS, encoding="utf-8")

html = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>IBBRU — Complexity, made simple.</title>
<meta name="description" content="IBBRU is an independent product design studio. We help teams solve problems, design better experiences, and build usable products.">
<meta property="og:title" content="IBBRU — Complexity, made simple.">
<meta property="og:description" content="Independent product design studio — product strategy, enterprise UX, design systems, 0-to-1 product design and brand video.">
<meta property="og:type" content="website">
<link rel="icon" href="assets/favicon.svg">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&amp;display=swap">
<link rel="stylesheet" href="styles.css">
<script>document.documentElement.classList.add('js');</script>
</head>
<body>
""" + content + MODAL + """
<script type="application/json" id="ib-data">""" + json.dumps(work, ensure_ascii=False).replace("</", "<\\/") + """</script>
<script src="app.js" defer></script>
<script>setTimeout(function(){document.querySelectorAll('[data-reveal]').forEach(function(e){e.classList.add('ib-in')})},3000);</script>
</body>
</html>
"""
(LIVE / "index.html").write_text(html, encoding="utf-8")

favicon = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">'
    '<rect width="64" height="64" rx="14" fill="#161826"/>'
    '<text x="32" y="43" font-family="Inter, system-ui, sans-serif" font-weight="700" '
    'font-size="30" letter-spacing="1" fill="#e9e9ed" text-anchor="middle">IB</text>'
    '<circle cx="32" cy="51" r="2.6" fill="#9184d9"/></svg>'
)
(LIVE / "assets" / "favicon.svg").write_text(favicon, encoding="utf-8")

print("rebuilt live/ — assets:", ", ".join(refs) or "none")
print("  books:", [(g["group"], len(g["cases"])) for g in work])